// <auto-generated />
using System;
using AutoConfig.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoConfig.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AutoConfig.Core.Entities.CarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.CarOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarOptions");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.Motorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Acceleration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Torque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Motorizations");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.VehicleConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MotorizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("MotorizationId");

                    b.HasIndex("UserId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("CarOptionCarOption", b =>
                {
                    b.Property<Guid>("IncompatibleWithId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncompatibleWithMeId")
                        .HasColumnType("TEXT");

                    b.HasKey("IncompatibleWithId", "IncompatibleWithMeId");

                    b.HasIndex("IncompatibleWithMeId");

                    b.ToTable("OptionIncompatibilities", (string)null);
                });

            modelBuilder.Entity("CarOptionMotorization", b =>
                {
                    b.Property<Guid>("RequiredByOptionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequiredMotorizationsId")
                        .HasColumnType("TEXT");

                    b.HasKey("RequiredByOptionsId", "RequiredMotorizationsId");

                    b.HasIndex("RequiredMotorizationsId");

                    b.ToTable("OptionMotorizationRequirements", (string)null);
                });

            modelBuilder.Entity("CarOptionVehicleConfiguration", b =>
                {
                    b.Property<Guid>("ConfigurationsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigurationsId", "OptionsId");

                    b.HasIndex("OptionsId");

                    b.ToTable("ConfigurationOptions", (string)null);
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.Motorization", b =>
                {
                    b.HasOne("AutoConfig.Core.Entities.CarModel", "Model")
                        .WithMany("Motorizations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.Quote", b =>
                {
                    b.HasOne("AutoConfig.Core.Entities.VehicleConfiguration", "Configuration")
                        .WithMany("Quotes")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoConfig.Core.Entities.User", "User")
                        .WithMany("Quotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.VehicleConfiguration", b =>
                {
                    b.HasOne("AutoConfig.Core.Entities.CarModel", "Model")
                        .WithMany("Configurations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoConfig.Core.Entities.Motorization", "Motorization")
                        .WithMany("Configurations")
                        .HasForeignKey("MotorizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoConfig.Core.Entities.User", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Motorization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarOptionCarOption", b =>
                {
                    b.HasOne("AutoConfig.Core.Entities.CarOption", null)
                        .WithMany()
                        .HasForeignKey("IncompatibleWithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoConfig.Core.Entities.CarOption", null)
                        .WithMany()
                        .HasForeignKey("IncompatibleWithMeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarOptionMotorization", b =>
                {
                    b.HasOne("AutoConfig.Core.Entities.CarOption", null)
                        .WithMany()
                        .HasForeignKey("RequiredByOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoConfig.Core.Entities.Motorization", null)
                        .WithMany()
                        .HasForeignKey("RequiredMotorizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarOptionVehicleConfiguration", b =>
                {
                    b.HasOne("AutoConfig.Core.Entities.VehicleConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoConfig.Core.Entities.CarOption", null)
                        .WithMany()
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.CarModel", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("Motorizations");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.Motorization", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.User", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("AutoConfig.Core.Entities.VehicleConfiguration", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
